### ISSUE TITLE
Update podspec file urls to point to the new repo

### ISSUE THREAD

**Issue by tomabin** [w-pay/sdk-wpay-ios#1]
#### Issue

[spec.source](https://github.com/w-pay/sdk-wpay-ios/blob/915ba3dc805a7bb5074243df280282f8b5373b55/VillageWalletSDK.podspec#L85) and [spec.homepage](https://github.com/w-pay/sdk-wpay-ios/blob/915ba3dc805a7bb5074243df280282f8b5373b55/VillageWalletSDK.podspec#L32) in  `VillageWalletSDK.podspec` is pointing to the old repo https://github.com/woolworthslimited/paysdk2-ios. This may be applicable to the [OpenAPI](https://github.com/w-pay/sdk-wpay-openapi-ios) repo too.

#### Expectation
The respective parameters should point to the new repo https://github.com/w-pay/sdk-wpay-ios

**Comment by tomabin** [comment]
@kierans

**Comment by kierans** [comment]
This has been done now.
